CREATE TABLE [dbo].[PersonVersions]
(
  Id INT IDENTITY PRIMARY KEY,
  PersonId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY (PersonId) REFERENCES Persons(Id),
  GivenName NVARCHAR(255) NOT NULL,
  Surname NVARCHAR(255) NOT NULL,
  Gender INT NOT NULL,
  BirthDate DATE,
  BirthLocation NVARCHAR(255),
  DeathDate DATE,
  DeathLocation NVARCHAR(255),
  Timestamp DATETIME NOT NULL DEFAULT GETDATE()
)